.env.example

docs: Better .env.example

---

src/main/kotlin/net/blockventuremc/modules/general/events/BuildEvents.kt
src/main/kotlin/net/blockventuremc/modules/general/events/ChatEvent.kt
src/main/kotlin/net/blockventuremc/modules/general/model/Ranks.kt
src/main/kotlin/net/blockventuremc/utils/ItemBuilder.kt
src/main/kotlin/net/blockventuremc/utils/RegisterManager.kt

Fix sonarqube issues

---

build.gradle.kts
src/main/kotlin/net/blockventuremc/BlockVenture.kt
src/main/kotlin/net/blockventuremc/cache/PlayerCache.kt
src/main/kotlin/net/blockventuremc/consts/Messages.kt
src/main/kotlin/net/blockventuremc/database/DatabaseManager.kt
src/main/kotlin/net/blockventuremc/database/functions/Users.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/RankCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/TestCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/events/BuildEvents.kt
src/main/kotlin/net/blockventuremc/modules/i18n/TranslationCache.kt
src/main/kotlin/net/blockventuremc/modules/placeholders/PlayerPlaceholder.kt
src/main/kotlin/net/blockventuremc/utils/CoroutineUtils.kt
src/main/kotlin/net/blockventuremc/utils/RegisterManager.kt
src/main/resources/paper-plugin.yml

> Fixxes all our issues we had when deploying the plugin

Make it working

---

src/main/kotlin/net/blockventuremc/extensions/JDKExtensions.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/BuildCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/model/Ranks.kt
src/main/kotlin/net/blockventuremc/modules/i18n/TranslationCache.kt
src/main/resources/translations/en-US.json

fix: Translations

---

src/main/kotlin/net/blockventuremc/BlockVenture.kt
src/main/kotlin/net/blockventuremc/cache/PlayerCache.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/OnlinetimeCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/events/PlayerLoadSaveListener.kt
src/main/resources/translations/en-US.json

fix: Onlinetime working

---

src/main/kotlin/net/blockventuremc/database/functions/Users.kt
src/main/kotlin/net/blockventuremc/database/model/DatabaseUser.kt
src/main/kotlin/net/blockventuremc/extensions/PlayerExtension.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/club/FlyCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/BuildCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/RankCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/TestCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/guests/OnlinetimeCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/model/Ranks.kt
src/main/kotlin/net/blockventuremc/utils/RegisterManager.kt
src/main/resources/translations/en-US.json

Adding new features to club members.
I tested it in game and via console.
Closes #36

feat: Fly Command

---

src/main/kotlin/net/blockventuremc/utils/RegisterManager.kt

feat: SentryExceptionHandling

---

src/main/kotlin/net/blockventuremc/cache/PlayerCache.kt
src/main/kotlin/net/blockventuremc/database/functions/Users.kt
src/main/kotlin/net/blockventuremc/database/model/DatabaseUser.kt
src/main/kotlin/net/blockventuremc/extensions/PlayerExtension.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/guests/MoneyCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/model/Ranks.kt
src/main/resources/translations/en-US.json

feat: VentureBits

---

build.gradle.kts
gradle.properties
src/main/kotlin/net/blockventuremc/consts/NameSpaces.kt
src/main/kotlin/net/blockventuremc/extensions/PlayerExtension.kt
src/main/kotlin/net/blockventuremc/modules/customblockdata/BlockDataListener.kt
src/main/kotlin/net/blockventuremc/modules/customblockdata/CustomBlockData.kt
src/main/kotlin/net/blockventuremc/modules/customblockdata/events/CustomBlockDataEvent.kt
src/main/kotlin/net/blockventuremc/modules/customblockdata/events/CustomBlockDataMoveEvent.kt
src/main/kotlin/net/blockventuremc/modules/customblockdata/events/CustomBlockDataRemoveEvent.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/LockCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/RankCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/events/LockableDoorListener.kt
src/main/resources/translations/en-US.json

feat: Lockable doors

---

src/main/kotlin/net/blockventuremc/modules/placeholders/PlayerPlaceholderManager.kt

hotfix: Changed relational placeholders

---

src/main/kotlin/net/blockventuremc/cache/PlayerCache.kt
src/main/kotlin/net/blockventuremc/database/DatabaseManager.kt
src/main/kotlin/net/blockventuremc/database/functions/BlockUserTable.kt
src/main/kotlin/net/blockventuremc/database/model/BlockUser.kt
src/main/kotlin/net/blockventuremc/extensions/PlayerExtension.kt
src/main/kotlin/net/blockventuremc/modules/archievements/AchievementManager.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/club/FlyCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/BuildCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/RankCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/guests/MoneyCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/guests/OnlinetimeCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/events/ActivityEvents.kt
src/main/kotlin/net/blockventuremc/modules/general/events/ChatEvent.kt
src/main/kotlin/net/blockventuremc/modules/general/manager/RankManager.kt
src/main/kotlin/net/blockventuremc/modules/placeholders/PlayerPlaceholderManager.kt
src/main/kotlin/net/blockventuremc/modules/titles/Title.kt

feat: Level System

---

src/main/kotlin/net/blockventuremc/extensions/PlayerExtension.kt
src/main/kotlin/net/blockventuremc/modules/warps/Warp.kt
src/main/kotlin/net/blockventuremc/modules/warps/WarpCommand.kt
src/main/kotlin/net/blockventuremc/modules/warps/WarpManager.kt
src/main/kotlin/net/blockventuremc/utils/FileConfig.kt
src/main/resources/translations/en-US.json

feat: WarpSystem

---

src/main/kotlin/net/blockventuremc/modules/warps/WarpCommand.kt
src/main/resources/translations/en-US.json

feat: Clickable Warps

---

build.gradle.kts

chore: Build script fixes

---

.env.example
build.gradle.kts
gradle.properties
src/main/kotlin/net/blockventuremc/BlockVenture.kt
src/main/kotlin/net/blockventuremc/modules/audioserver/MovementListener.kt

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
is part of #40

feat: Added AudioServerAPI

---

gradle.properties
src/main/kotlin/net/blockventuremc/BlockVenture.kt
src/main/kotlin/net/blockventuremc/modules/audioserver/MovementListener.kt

feat: Better AudioServer

---

.github/workflows/build.yml
.github/workflows/dokka.yml

chore: Workflow Secrets

---

src/main/kotlin/net/blockventuremc/modules/general/commands/crew/AreaCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/SkullCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/WorldCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/guests/SpawnCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/model/Ranks.kt
src/main/resources/translations/en-US.json

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull
request changes UI.
Fixes #109

feat: Basic Commands

---

src/main/kotlin/net/blockventuremc/modules/general/events/ServerPingListener.kt

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull
request changes UI.
Fixes #111

feat: Motd

---

src/main/kotlin/net/blockventuremc/VentureLibs.kt
src/main/kotlin/net/blockventuremc/modules/warps/WarpManager.kt

Fixed a bug when loading warps of different (unloaded) worlds

fix: Warp problems

---

build.gradle.kts
gradle.properties
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/SkullCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/events/EquipableItemListener.kt
src/main/kotlin/net/blockventuremc/modules/titles/Title.kt
src/main/kotlin/net/blockventuremc/modules/titles/TitleCategory.kt
src/main/kotlin/net/blockventuremc/modules/titles/TitleSelectionGui.kt
src/main/kotlin/net/blockventuremc/utils/itembuilder/ItemBuilder.kt

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull
request changes UI.
Fixes #115

feat: Equipables

---

build.gradle.kts
gradle.properties
src/main/kotlin/net/blockventuremc/VentureLibs.kt
src/main/kotlin/net/blockventuremc/modules/general/events/ActivityEvents.kt

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull
request changes UI.
Fixes #

chore: Update audioserver

---

build.gradle.kts
gradle.properties
src/main/kotlin/net/blockventuremc/JavaDotEnv.java
src/main/kotlin/net/blockventuremc/VentureLibs.kt
src/main/kotlin/net/blockventuremc/extensions/DiscordExtensions.kt
src/main/kotlin/net/blockventuremc/modules/discord/commands/LinkCommand.kt
src/main/kotlin/net/blockventuremc/utils/RegisterManager.kt
src/main/resources/paper-plugin.yml

fix: use another reflections lib

---

src/main/kotlin/net/blockventuremc/modules/general/commands/crew/ClearChatCommand.kt

feat: ClearChat Command

---

src/main/kotlin/net/blockventuremc/modules/animations/faucets/FaucetAnimation.kt
src/main/kotlin/net/blockventuremc/modules/animations/faucets/FaucetListener.kt

feat: FaucetAnimation

---

src/main/kotlin/net/blockventuremc/modules/animations/faucets/FaucetAnimation.kt
src/main/kotlin/net/blockventuremc/modules/animations/faucets/FaucetListener.kt

feat: change sounds and add animation checks

---

src/main/kotlin/net/blockventuremc/modules/general/commands/crew/RankCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/manager/RankManager.kt

feat: Reloadable Ranks

---

src/main/kotlin/net/blockventuremc/VentureLibs.kt
src/main/kotlin/net/blockventuremc/extensions/JDKExtensions.kt
src/main/kotlin/net/blockventuremc/modules/rides/track/TrackCommand.kt
src/main/kotlin/net/blockventuremc/modules/rides/track/TrackManager.kt
src/main/kotlin/net/blockventuremc/modules/rides/track/TrackRide.kt

feat: Track loading and saving

---

build.gradle.kts
gradle.properties
src/main/kotlin/net/blockventuremc/VentureLibs.kt
src/main/kotlin/net/blockventuremc/extensions/MathExtensions.kt
src/main/kotlin/net/blockventuremc/modules/structures/Seat.kt

feat: SmoothCoastersAPI

---

src/main/kotlin/net/blockventuremc/VentureLibs.kt
src/main/kotlin/net/blockventuremc/modules/general/commands/crew/BuildCommand.kt
src/main/kotlin/net/blockventuremc/modules/general/events/custom/AFKChangeEvent.kt
src/main/kotlin/net/blockventuremc/modules/rides/track/TrackCommand.kt
src/main/kotlin/net/blockventuremc/modules/rides/track/TrackRide.kt
src/main/kotlin/net/blockventuremc/modules/structures/Seat.kt
src/main/kotlin/net/blockventuremc/modules/structures/Train.kt
src/main/kotlin/net/blockventuremc/modules/structures/events/StructureEvents.kt
src/main/kotlin/net/blockventuremc/modules/structures/events/TrainEnterEvent.kt
src/main/kotlin/net/blockventuremc/modules/structures/events/TrainExitEvent.kt
src/main/kotlin/net/blockventuremc/modules/titles/TitleOverheadDisplayListener.kt
src/main/kotlin/net/blockventuremc/modules/titles/events/TitleChangedEvent.kt
src/main/resources/translations/de-DE.json

fix: Titles

---

src/main/kotlin/net/blockventuremc/modules/general/events/PlayerLoadSaveListener.kt

feat: Tablist header and footer

---

src/main/kotlin/net/blockventuremc/utils/PlaceholderFunctions.kt

Added a regex for commands

---

src/main/kotlin/net/blockventuremc/modules/general/events/ChatEvent.kt
src/main/kotlin/net/blockventuremc/utils/PlaceholderFunctions.kt
src/main/resources/translations/en-US.json

feat: Open profile on chatname

---

src/main/kotlin/net/blockventuremc/extensions/InventoryExtension.kt
src/main/kotlin/net/blockventuremc/modules/general/events/ItemClickListener.kt
src/main/kotlin/net/blockventuremc/modules/warps/ParkArea.kt
src/main/kotlin/net/blockventuremc/modules/warps/Warp.kt
src/main/kotlin/net/blockventuremc/modules/warps/WarpCommand.kt
src/main/kotlin/net/blockventuremc/modules/warps/WarpManager.kt
src/main/kotlin/net/blockventuremc/modules/warps/gui/WarpGui.kt
src/main/kotlin/net/blockventuremc/modules/warps/gui/WarpGuiListener.kt
src/main/kotlin/net/blockventuremc/utils/itembuilder/ItemBuilder.kt
src/main/resources/translations/en-US.json

feat: WarpMenu

---

src/main/kotlin/net/blockventuremc/modules/general/commands/crew/TestGuiCommand.kt
src/main/kotlin/net/blockventuremc/utils/CharRepo.kt

feat: CustomInventories

---

.github/CONTRIBUTING.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
docs/CONTRIBUTORS.md

Add contributing guidelines and code of conduct to the repository.
* Add `CONTRIBUTING.md` with guidelines on how to contribute, submit issues, and pull requests, and coding standards and best practices.
* Add `CODE_OF_CONDUCT.md` with guidelines for respectful and inclusive behavior and contact information for reporting issues.
* Modify `README.md` to include sections on contributing guidelines and code of conduct with links to the respective files.
* Add `docs/CONTRIBUTORS.md` with a list of contributors and guidelines for adding new contributors.
* Add `.github/CONTRIBUTING.md` with contributing guidelines similar to the main `CONTRIBUTING.md`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/BlockVentureMC/VentureLibs?shareId=8816dea6- …

Add contributing guidelines and code of conduct
